name: machine-learning-hats-2021
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - uproot
    - h5py
    - tensorflow-mkl>=2
    - scikit-learn
    - scikit-optimize
    - matplotlib
    - pandas
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - ipykernel
    - tqdm
    - jupyter